// src/services/mockRooms.js
import {
  hotel1,
  hotel2,
  hotel3,
  hotel4,
  hotel5,
  hotel6,
  hotel7,
  hotel8,
  hotel9,
} from "../assets/images/img";

export const mockRooms = [
  {
    id: 1,
    image: hotel1,
    gallery: [hotel1, hotel2, hotel3, hotel4],
    title: "Deluxe Ocean View",
    guests: 2,
    size: 35,
    beds: ["1 Giường King size"],
    view: "Quang cảnh biển",
    address: "36 Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",
    descShort: "Phòng hiện đại với view biển tuyệt đẹp.",
    descLong:
      "Deluxe Ocean View mang đến không gian nghỉ dưỡng sang trọng, với tầm nhìn toàn cảnh ra biển Đông. Nội thất hiện đại, ban công rộng thoáng, phòng tắm cao cấp với bồn tắm và vòi sen riêng biệt. Phù hợp cho các cặp đôi tận hưởng kỳ nghỉ lãng mạn.",
    price: "2.000.000",
    oldPrice: "2.500.000",
    discount: 20,
    booking: {
      nights: 2,
      checkIn: "2025-09-01",
      checkOut: "2025-09-03",
      checkInDetail: "Thứ Hai từ 14:00",
      checkOutDetail: "Thứ Tư đến 12:00",
    },
    amenities: {
      wifi: true,
      airConditioning: true,
      nonSmoking: true,
      hairDryer: true,
      petsAllowed: false,
      pool: true,
      gym: true,
      spa: true,
    },
    reviews: [
      { user: "Nguyễn Văn A", stars: 5, comment: "Phòng rất đẹp và sạch sẽ!" },
      {
        user: "Trần Thị B",
        stars: 4,
        comment: "Dịch vụ tốt nhưng ăn sáng chưa phong phú.",
      },
      {
        user: "Lê Văn C",
        stars: 5,
        comment: "View biển tuyệt vời, sẽ quay lại.",
      },
      { user: "Phạm Thị D", stars: 3, comment: "Ổn nhưng phòng hơi nhỏ." },
    ],
  },
  {
    id: 2,
    image: hotel2,
    gallery: [hotel2, hotel3, hotel4],
    title: "Superior Garden Room",
    guests: 3,
    size: 40,
    beds: ["1 Giường Queen size", "1 Giường đơn"],
    view: "Quang cảnh vườn",
    address: "12 Lê Lợi, Hải Châu, Đà Nẵng",
    descShort: "Không gian yên tĩnh, thiết kế ấm cúng.",
    descLong:
      "Superior Garden Room hướng ra khu vườn xanh mát, mang đến cảm giác thư thái, dễ chịu. Thiết kế nội thất hiện đại kết hợp với tông màu ấm áp, thích hợp cho gia đình nhỏ hoặc nhóm bạn.",
    price: "1.800.000",
    oldPrice: "2.200.000",
    discount: 18,
    booking: {
      nights: 3,
      checkIn: "2025-09-05",
      checkOut: "2025-09-08",
      checkInDetail: "Thứ Năm từ 14:00",
      checkOutDetail: "Chủ Nhật đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      petsAllowed: true,
      nonSmoking: true,
    },
  },
  {
    id: 3,
    image: hotel3,
    gallery: [hotel3, hotel4, hotel5],
    title: "Premium Suite City View",
    guests: 2,
    size: 55,
    beds: ["1 Giường King size"],
    view: "Quang cảnh thành phố",
    address: "88 Bạch Đằng, Hải Châu, Đà Nẵng",
    descShort: "Suite cao cấp với phòng khách riêng.",
    descLong:
      "Premium Suite City View mang đến trải nghiệm sang trọng với phòng khách riêng biệt và tầm nhìn toàn cảnh thành phố về đêm. Không gian rộng rãi, nội thất tinh tế, phù hợp cho du khách muốn tận hưởng sự tiện nghi bậc nhất.",
    price: "3.500.000",
    oldPrice: "4.200.000",
    discount: 17,
    booking: {
      nights: 2,
      checkIn: "2025-09-07",
      checkOut: "2025-09-09",
      checkInDetail: "Thứ Bảy từ 14:00",
      checkOutDetail: "Thứ Hai đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 4,
    image: hotel4,
    gallery: [hotel4, hotel5, hotel6],
    title: "Wink Luxe Family Room",
    guests: 5,
    size: 50,
    beds: ["2 Giường Queen size", "1 Giường tầng"],
    view: "Quang cảnh núi và thành phố",
    address: "88 Nguyễn Tất Thành, Hòa Vang, Đà Nẵng",
    descShort: "Phòng gia đình rộng rãi, tiện nghi.",
    descLong:
      "Wink Luxe Family Room được thiết kế cho các gia đình đông người với không gian rộng rãi, ban công lớn, nội thất hiện đại. Phòng có tầm nhìn ra cả núi và thành phố, tạo nên trải nghiệm nghỉ dưỡng hoàn hảo.",
    price: "3.200.000",
    oldPrice: "3.800.000",
    discount: 15,
    booking: {
      nights: 4,
      checkIn: "2025-09-10",
      checkOut: "2025-09-14",
      checkInDetail: "Thứ Ba từ 14:00",
      checkOutDetail: "Thứ Bảy đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 5,
    image: hotel5,
    gallery: [hotel5, hotel6, hotel7],
    title: "Standard Twin Room",
    guests: 2,
    size: 28,
    beds: ["2 Giường đơn"],
    view: "Một phần quang cảnh biển",
    address: "15 Trần Phú, Hải Châu, Đà Nẵng",
    descShort: "Phòng nhỏ gọn, giá tốt.",
    descLong:
      "Standard Twin Room có thiết kế tối giản, diện tích vừa phải nhưng đầy đủ tiện nghi. Phù hợp cho cặp đôi hoặc bạn bè đi du lịch muốn tiết kiệm chi phí nhưng vẫn thoải mái.",
    price: "1.200.000",
    oldPrice: "1.500.000",
    discount: 20,
    booking: {
      nights: 1,
      checkIn: "2025-09-12",
      checkOut: "2025-09-13",
      checkInDetail: "Thứ Năm từ 14:00",
      checkOutDetail: "Thứ Sáu đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 6,
    image: hotel6,
    gallery: [hotel6, hotel7, hotel8],
    title: "Executive Suite Oceanfront",
    guests: 3,
    size: 70,
    beds: ["1 Giường King size", "1 Sofa bed"],
    view: "Hướng biển trực diện",
    address: "123 Phạm Văn Đồng, Sơn Trà, Đà Nẵng",
    descShort: "Suite sang trọng với ban công lớn.",
    descLong:
      "Executive Suite Oceanfront sở hữu ban công rộng lớn hướng trực diện biển Đông. Không gian sang trọng, hiện đại, phù hợp cho các kỳ nghỉ dài ngày hoặc gia đình nhỏ.",
    price: "4.500.000",
    oldPrice: "5.200.000",
    discount: 14,
    booking: {
      nights: 5,
      checkIn: "2025-09-15",
      checkOut: "2025-09-20",
      checkInDetail: "Chủ Nhật từ 14:00",
      checkOutDetail: "Thứ Sáu đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 7,
    image: hotel7,
    gallery: [hotel7, hotel8, hotel9],
    title: "Penthouse Luxury Villa",
    guests: 6,
    size: 120,
    beds: ["3 Giường King size"],
    view: "Biển và hồ bơi riêng",
    address: "Villa Zone, Sơn Trà, Đà Nẵng",
    descShort: "Biệt thự cao cấp với hồ bơi riêng.",
    descLong:
      "Penthouse Luxury Villa mang đến trải nghiệm nghỉ dưỡng thượng lưu với hồ bơi riêng, phòng rộng lớn, nội thất hiện đại và view biển tuyệt đẹp. Lựa chọn hoàn hảo cho gia đình hoặc nhóm bạn đông người.",
    price: "12.000.000",
    oldPrice: "14.000.000",
    discount: 12,
    booking: {
      nights: 2,
      checkIn: "2025-09-18",
      checkOut: "2025-09-20",
      checkInDetail: "Thứ Tư từ 14:00",
      checkOutDetail: "Thứ Sáu đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 8,
    image: hotel8,
    gallery: [hotel8, hotel9, hotel1],
    title: "Studio Apartment",
    guests: 2,
    size: 45,
    beds: ["1 Giường Queen size"],
    view: "Một phần thành phố",
    address: "21 Hoàng Sa, Sơn Trà, Đà Nẵng",
    descShort: "Căn hộ studio tiện nghi, có bếp nhỏ.",
    descLong:
      "Studio Apartment thích hợp cho khách ở dài ngày. Phòng được trang bị bếp nhỏ, ban công thoáng mát nhìn ra thành phố. Thiết kế hiện đại, đầy đủ tiện nghi như một căn hộ thu nhỏ.",
    price: "1.900.000",
    oldPrice: "2.300.000",
    discount: 17,
    booking: {
      nights: 6,
      checkIn: "2025-09-20",
      checkOut: "2025-09-26",
      checkInDetail: "Thứ Sáu từ 14:00",
      checkOutDetail: "Thứ Năm đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
  {
    id: 9,
    image: hotel9,
    gallery: [hotel9, hotel1, hotel2],
    title: "Junior Suite Garden View",
    guests: 2,
    size: 48,
    beds: ["1 Giường King size"],
    view: "Quang cảnh vườn",
    address: "5 Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
    descShort: "Junior Suite sang trọng, nhìn ra vườn.",
    descLong:
      "Junior Suite Garden View được thiết kế tinh tế, không gian rộng rãi và yên tĩnh. View vườn xanh mát giúp du khách thư giãn, đặc biệt phù hợp cho các cặp đôi.",
    price: "2.800.000",
    oldPrice: "3.300.000",
    discount: 15,
    booking: {
      nights: 3,
      checkIn: "2025-09-23",
      checkOut: "2025-09-26",
      checkInDetail: "Thứ Hai từ 14:00",
      checkOutDetail: "Thứ Năm đến 12:00",
    },
    amenities: {
      airConditioning: true,
      wifi: true,
      nonSmoking: true,
    },
  },
];
